[package]
name = "openal_stats_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
interprocess = { version = "2.2.2", features = ["tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.7.13"
openal_stats_common = { path = "../openal_stats_common"}
